"""empty message

Revision ID: 175e308ae73a
Revises: db10b48f6dc4
Create Date: 2024-08-20 21:41:23.205592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175e308ae73a'
down_revision = 'db10b48f6dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('multiplier',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('multiplier',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
