"""empty message

Revision ID: 529b1135ae86
Revises: 3d94922d1216
Create Date: 2024-08-20 08:28:18.828648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529b1135ae86'
down_revision = '3d94922d1216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('locations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locations', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['locations'], ['location_name'])

    # ### end Alembic commands ###
