"""empty message

Revision ID: 67efca7eb462
Revises: 529b1135ae86
Create Date: 2024-08-20 08:30:00.509236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67efca7eb462'
down_revision = '529b1135ae86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('timeslot', sa.INTEGER(), nullable=True),
    sa.Column('multiplier', sa.INTEGER(), nullable=True),
    sa.Column('locations', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['locations'], ['locations.location_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
