"""empty message

Revision ID: b43559d3e0be
Revises: 14e9ee78430b
Create Date: 2024-08-20 07:54:52.922509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43559d3e0be'
down_revision = '14e9ee78430b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['location_name'], ['location_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###
